### ISSUE TITLE
Wavin component can't set Operation

### ISSUE THREAD

**Issue by MTrab** [heinekmadsen/esphome_components#1]
When selecting Off in the operation type, nothing happens.

And if a thermostat is in Off mode, there is no possibility to switch it back to heat

![image](https://user-images.githubusercontent.com/14296463/128854504-f3c50b9c-48b5-4797-b3bd-9dadb2e458c6.png)

**Comment by heinekmadsen** [comment]
Operation mode will change when target temperature is above current temperature.

**Comment by MTrab** [comment]
Correct, but setting stby mode is not possible, as it was when running the MQTT firmware.
Would be an awesome addition to this ;)
