### ISSUE TITLE
See heating state in Homeassistant

### ISSUE THREAD

**Issue by mathias-jakobsen** [heinekmadsen/esphome_components#11]
In Homeassistant, it is currently not possible to see whether the room is actively heating.
Is it possible to add this?

**Comment by heinekmadsen** [comment]
It's already in dev branch... Will merge it into main in a few days... it's  a breaking change since it will require everyone using the main branch to update their yaml

**Comment by mathias-jakobsen** [comment]
That is awesome! And btw, thanks for the hard work :-)
