### ISSUE TITLE
Wavin doesn't seem compatible with ESPHome 2022.7

### ISSUE THREAD

**Issue by MTrab** [heinekmadsen/esphome_components#16]
Just updated to dev channel on my ESPHome, and it seems like the Wavin component is not compatible.

![image](https://user-images.githubusercontent.com/14296463/175543878-04e52b40-219f-4738-a38d-f3e6893309af.png)

**Comment by Jopand** [comment]
Same issue here with Esphome 2022.6.2

**Comment by heinekmadsen** [comment]
Should be resolved by @ricobach 's amazing work on https://github.com/heinekmadsen/esphome_components/pull/41 which is merged
