### ISSUE TITLE
Climate current temperature incorrect

### ISSUE THREAD

**Issue by mathias-jakobsen** [heinekmadsen/esphome_components#7]
The current temperature of the climate control is rounded up to the nearest 0.5 degrees celcius. Can it be changed to represent the true temperature?

Picture 1, shows the climate control:
![kitchen_climate](https://user-images.githubusercontent.com/55285073/153489896-eed7dba3-5b90-4e74-8c50-975cf7851f54.png)

Picture 2, shows the sensor:
![kitchen_sensor](https://user-images.githubusercontent.com/55285073/153489911-c644b789-d84d-40e7-bbc5-d38b1e3a3b64.png)

**Comment by heinekmadsen** [comment]
Wavin Ahc 9000 v2 shows .1 degrees and rounds set temperature to .5 degress
